; PlatformIO Project Configuration File

[env:heltec_wifi_lora_32_V3]
platform = espressif32@6.9.0
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200

lib_deps =
    HelTecAutomation/Heltec ESP32 Dev-Boards @ 2.1.7

build_flags =
    -D HELTEC_BOARD=30
    -D HELTEC_WIFI_LORA_32_V3
    -D WIFI_LORA_32_V3
    -D MCU_ESP32_S3
    -D RADIO_CHIP_SX1262
    -D SLOW_CLK_TPYE=0
    -D LoRaWAN_DEBUG_LEVEL=3
    -D GPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT